version: '3.7'

services:
  battery_simulator_backend:
    container_name: simulationNotification
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SIMULATION_API_URL=http://battery_simulator:8084
    networks:
      - battery_simulator_network

networks:
  battery_simulator_network:
    driver: bridge
    external: true
